### PR TITLE
Fixed paging issue on app list page

### PR DESCRIPTION
**Pull request by bill-cooper**
The is a fix for the paging issue on the dashboard.  Associated with trello card "Dashboard can only display a maximum of 20 cnq apps"

### CODE REVIEW

**Comment by bill-cooper** [comment]
@agilenut - I know you had looked at this one because you were asking about coffeescript.  Did you get a chance to go through this one or should I expect a review when you get back from vacation?

**Comment by agilenut** [comment]
I didn’t feel like I had time to do a solid review but I’m going to try to do it before we leave. 

Eric

**Comment by bill-cooper** [comment]
No prob and no rush.  Just checking on the status.

**Comment by agilenut** [comment]
Ok. Looks good.

**Pull request merged**
